spring:
  application:
    name: auth-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      name: auth-service
      profile: dev
